import type { PatientRecord } from "./types";

export const initialPatients: PatientRecord[] = [
  {
    id: "patient1",
    patientName: "Nguyễn Văn A (FH - 5 Visits)",
    status: "alive",
    visits: [
      {
        id: "p1-v1",
        visitDate: "Tuần 0 (Khám đầu)",
        clinicalNotes: "Lần đầu phát hiện tăng LDL-C rất cao. Tiền sử gia đình có bố bị nhồi máu cơ tim sớm (50 tuổi). Được chẩn đoán Tăng Cholesterol máu gia đình (FH) dự phòng tiên phát. Điều trị khởi trị đề xuất: Khởi trị ngay Statin hoạt lực mạnh Atorvastatin 40mg uống tối.",
        patientData: {
          name: "Nguyễn Văn A",
          age: 45,
          sex: "male",
          riskRegion: "low",
          smokingStatus: false,
          sbp: 140,
          dbp: 85,
          totalChol: 8.5,
          hdlChol: 1.2,
          ldlChol: 6.2,
          triglycerides: 2.1,
          unit: "mmol",
          hasAscvd: false,
          ascvdType: "primary",
          diabetes: "none",
          dmDuration: 0,
          dmTargetOrganDamage: false,
          dmRiskFactorsCount: 0,
          ckd: "none",
          hasFh: true,
          fhHasMajorRiskFactor: false,
          hasSubclinicalPlaque: false,
          hasPrematureFamilyHistory: true,
          hasLpaElevated: false,
          hasHiv: false,
          hasCancerToxicityRisk: false,
          useDietarySupplements: false
        }
      },
      {
        id: "p1-v2",
        visitDate: "Tuần 6 (Tái khám)",
        clinicalNotes: "Tái khám sau 6 tuần điều trị Atorvastatin 40mg. LDL-C giảm từ 6.2 mmol/L xuống 4.2 mmol/L (~32%). Tuy nhiên vẫn chưa đạt đích mục tiêu (< 1.4 mmol/L). Bệnh nhân dung nạp thuốc tốt, không có đau cơ. Khuyến cáo tăng bậc điều trị: Atorvastatin 80mg uống tối + phối hợp Ezetimibe 10mg/ngày.",
        patientData: {
          name: "Nguyễn Văn A",
          age: 45,
          sex: "male",
          riskRegion: "low",
          smokingStatus: false,
          sbp: 135,
          dbp: 82,
          totalChol: 6.5,
          hdlChol: 1.2,
          ldlChol: 4.2,
          triglycerides: 1.8,
          unit: "mmol",
          hasAscvd: false,
          ascvdType: "primary",
          diabetes: "none",
          dmDuration: 0,
          dmTargetOrganDamage: false,
          dmRiskFactorsCount: 0,
          ckd: "none",
          hasFh: true,
          fhHasMajorRiskFactor: false,
          hasSubclinicalPlaque: false,
          hasPrematureFamilyHistory: true,
          hasLpaElevated: false,
          hasHiv: false,
          hasCancerToxicityRisk: false,
          useDietarySupplements: false
        }
      },
      {
        id: "p1-v3",
        visitDate: "Tuần 12 (Tái khám)",
        clinicalNotes: "Tái khám sau 6 tuần dùng Atorvastatin 80mg + Ezetimibe 10mg. LDL-C giảm tiếp xuống 2.6 mmol/L (~58% so với nền ban đầu). Vẫn chưa đạt đích mục tiêu (< 1.4 mmol/L). Dựa trên khuyến nghị Cập nhật ESC 2025, quyết định phối hợp thêm Bempedoic Acid 180mg/ngày.",
        patientData: {
          name: "Nguyễn Văn A",
          age: 45,
          sex: "male",
          riskRegion: "low",
          smokingStatus: false,
          sbp: 130,
          dbp: 80,
          totalChol: 4.9,
          hdlChol: 1.2,
          ldlChol: 2.6,
          triglycerides: 1.6,
          unit: "mmol",
          hasAscvd: false,
          ascvdType: "primary",
          diabetes: "none",
          dmDuration: 0,
          dmTargetOrganDamage: false,
          dmRiskFactorsCount: 0,
          ckd: "none",
          hasFh: true,
          fhHasMajorRiskFactor: false,
          hasSubclinicalPlaque: false,
          hasPrematureFamilyHistory: true,
          hasLpaElevated: false,
          hasHiv: false,
          hasCancerToxicityRisk: false,
          useDietarySupplements: false
        }
      },
      {
        id: "p1-v4",
        visitDate: "Tuần 18 (Tái khám)",
        clinicalNotes: "Tái khám sau 6 tuần dùng thêm Bempedoic Acid. LDL-C đáp ứng tốt giảm xuống 1.6 mmol/L (~74% giảm so với nền). Rất gần đích mục tiêu 1.4 mmol/L. Thảo luận phối hợp thêm kháng thể đơn dòng PCSK9 inhibitor (Evolocumab 140mg tiêm dưới da mỗi 2 tuần) để kiểm soát mỡ máu tối đa cho ca bệnh FH này.",
        patientData: {
          name: "Nguyễn Văn A",
          age: 45,
          sex: "male",
          riskRegion: "low",
          smokingStatus: false,
          sbp: 128,
          dbp: 80,
          totalChol: 3.9,
          hdlChol: 1.2,
          ldlChol: 1.6,
          triglycerides: 1.5,
          unit: "mmol",
          hasAscvd: false,
          ascvdType: "primary",
          diabetes: "none",
          dmDuration: 0,
          dmTargetOrganDamage: false,
          dmRiskFactorsCount: 0,
          ckd: "none",
          hasFh: true,
          fhHasMajorRiskFactor: false,
          hasSubclinicalPlaque: false,
          hasPrematureFamilyHistory: true,
          hasLpaElevated: false,
          hasHiv: false,
          hasCancerToxicityRisk: false,
          useDietarySupplements: false
        }
      },
      {
        id: "p1-v5",
        visitDate: "Tuần 24 (Đích đạt)",
        clinicalNotes: "Tái khám tuần 24. Kết quả tuyệt vời sau 6 tuần dùng PCSK9i: LDL-C giảm sâu xuống còn 0.8 mmol/L. Đạt hoàn hảo mục tiêu đích điều trị (< 1.4 mmol/L và giảm >50% so với ban đầu). Bệnh nhân khỏe mạnh, dung nạp tốt toàn bộ phác đồ. Tiếp tục phác đồ duy trì.",
        patientData: {
          name: "Nguyễn Văn A",
          age: 45,
          sex: "male",
          riskRegion: "low",
          smokingStatus: false,
          sbp: 125,
          dbp: 78,
          totalChol: 3.1,
          hdlChol: 1.2,
          ldlChol: 0.8,
          triglycerides: 1.4,
          unit: "mmol",
          hasAscvd: false,
          ascvdType: "primary",
          diabetes: "none",
          dmDuration: 0,
          dmTargetOrganDamage: false,
          dmRiskFactorsCount: 0,
          ckd: "none",
          hasFh: true,
          fhHasMajorRiskFactor: false,
          hasSubclinicalPlaque: false,
          hasPrematureFamilyHistory: true,
          hasLpaElevated: false,
          hasHiv: false,
          hasCancerToxicityRisk: false,
          useDietarySupplements: false
        }
      }
    ]
  },
  {
    id: "patient2",
    patientName: "Trần Thị B (ACS & Đau cơ Statin - 10 Visits)",
    status: "alive",
    visits: [
      {
        id: "p2-v1",
        visitDate: "Tuần 0 (Nằm viện ACS)",
        clinicalNotes: "Bệnh nhân nữ 62 tuổi, nhập viện vì Hội chứng vành cấp (ACS) - Nhồi máu cơ tim cấp. Đã được can thiệp đặt stent mạch vành thành công. LDL-C chưa điều trị là 4.5 mmol/L. Áp dụng chiến lược 'Strike early, strike strong' của ESC 2025: Khởi trị ngay phối hợp Statin hoạt lực cực mạnh Rosuvastatin 40mg + Ezetimibe 10mg đồng thời ngay tại viện.",
        patientData: {
          name: "Trần Thị B",
          age: 62,
          sex: "female",
          riskRegion: "very_high",
          smokingStatus: true,
          sbp: 155,
          dbp: 95,
          totalChol: 7.2,
          hdlChol: 1.0,
          ldlChol: 4.5,
          triglycerides: 2.5,
          unit: "mmol",
          hasAscvd: true,
          ascvdType: "secondary",
          diabetes: "none",
          dmDuration: 0,
          dmTargetOrganDamage: false,
          dmRiskFactorsCount: 0,
          ckd: "none",
          hasFh: false,
          fhHasMajorRiskFactor: false,
          hasSubclinicalPlaque: true,
          hasPrematureFamilyHistory: false,
          hasLpaElevated: true,
          hasHiv: false,
          hasCancerToxicityRisk: false,
          useDietarySupplements: false
        }
      },
      {
        id: "p2-v2",
        visitDate: "Tuần 4 (Đau cơ cấp)",
        clinicalNotes: "Tái khám sau 4 tuần xuất viện. Bệnh nhân than phiền đau nhức cơ nặng toàn thân, mệt mỏi rã rời, yếu 2 chi dưới (Myalgia). Xét nghiệm thấy AST/ALT tăng gấp 3.5 lần giới hạn bình thường. Chẩn đoán: Không dung nạp statin cường độ cao (Statin intolerance). Quyết định: Ngừng ngay Rosuvastatin, chuyển sang điều trị thay thế bằng phối hợp Bempedoic Acid 180mg + Ezetimibe 10mg (Khuyến nghị Class I - ESC 2025).",
        patientData: {
          name: "Trần Thị B",
          age: 62,
          sex: "female",
          riskRegion: "very_high",
          smokingStatus: true,
          sbp: 135,
          dbp: 85,
          totalChol: 5.8,
          hdlChol: 1.0,
          ldlChol: 2.8,
          triglycerides: 2.2,
          unit: "mmol",
          hasAscvd: true,
          ascvdType: "secondary",
          diabetes: "none",
          dmDuration: 0,
          dmTargetOrganDamage: false,
          dmRiskFactorsCount: 0,
          ckd: "none",
          hasFh: false,
          fhHasMajorRiskFactor: false,
          hasSubclinicalPlaque: true,
          hasPrematureFamilyHistory: false,
          hasLpaElevated: true,
          hasHiv: false,
          hasCancerToxicityRisk: false,
          useDietarySupplements: false
        }
      },
      {
        id: "p2-v3",
        visitDate: "Tuần 8 (Tái khám)",
        clinicalNotes: "Tái khám tuần 8. LDL-C là 2.8 mmol/L. Bệnh nhân đã hết hoàn toàn triệu chứng đau cơ, men gan AST/ALT trở lại bình thường. Do bệnh nhân thuộc nhóm nguy cơ RẤT CAO phòng ngừa thứ phát (sau ACS), đích LDL-C bắt buộc là < 1.4 mmol/L. Quyết định phối hợp thêm kháng thể đơn dòng PCSK9 inhibitor (Evolocumab 140mg tiêm dưới da mỗi 2 tuần).",
        patientData: {
          name: "Trần Thị B",
          age: 62,
          sex: "female",
          riskRegion: "very_high",
          smokingStatus: true,
          sbp: 130,
          dbp: 80,
          totalChol: 5.5,
          hdlChol: 1.0,
          ldlChol: 2.8,
          triglycerides: 2.1,
          unit: "mmol",
          hasAscvd: true,
          ascvdType: "secondary",
          diabetes: "none",
          dmDuration: 0,
          dmTargetOrganDamage: false,
          dmRiskFactorsCount: 0,
          ckd: "none",
          hasFh: false,
          fhHasMajorRiskFactor: false,
          hasSubclinicalPlaque: true,
          hasPrematureFamilyHistory: false,
          hasLpaElevated: true,
          hasHiv: false,
          hasCancerToxicityRisk: false,
          useDietarySupplements: false
        }
      },
      {
        id: "p2-v4",
        visitDate: "Tuần 12 (Đích đạt)",
        clinicalNotes: "Tái khám tuần 12. LDL-C đo được là 1.3 mmol/L, chính thức đạt đích mục tiêu khuyến nghị (< 1.4 mmol/L và giảm >50%). Huyết áp kiểm soát tốt ở mức 125/80 mmHg. Bệnh nhân cảm thấy khỏe mạnh và tuân thủ rất tốt.",
        patientData: {
          name: "Trần Thị B",
          age: 62,
          sex: "female",
          riskRegion: "very_high",
          smokingStatus: true,
          sbp: 125,
          dbp: 80,
          totalChol: 4.0,
          hdlChol: 1.0,
          ldlChol: 1.3,
          triglycerides: 1.8,
          unit: "mmol",
          hasAscvd: true,
          ascvdType: "secondary",
          diabetes: "none",
          dmDuration: 0,
          dmTargetOrganDamage: false,
          dmRiskFactorsCount: 0,
          ckd: "none",
          hasFh: false,
          fhHasMajorRiskFactor: false,
          hasSubclinicalPlaque: true,
          hasPrematureFamilyHistory: false,
          hasLpaElevated: true,
          hasHiv: false,
          hasCancerToxicityRisk: false,
          useDietarySupplements: false
        }
      },
      {
        id: "p2-v5",
        visitDate: "Tuần 16 (Tái khám)",
        clinicalNotes: "Theo dõi định kỳ tuần 16. Mỡ máu và huyết áp ổn định tuyệt đối. Dung nạp thuốc hoàn hảo. Tiếp tục duy trì phác đồ hiện tại.",
        patientData: {
          name: "Trần Thị B",
          age: 62,
          sex: "female",
          riskRegion: "very_high",
          smokingStatus: true,
          sbp: 125,
          dbp: 78,
          totalChol: 3.9,
          hdlChol: 1.0,
          ldlChol: 1.25,
          triglycerides: 1.75,
          unit: "mmol",
          hasAscvd: true,
          ascvdType: "secondary",
          diabetes: "none",
          dmDuration: 0,
          dmTargetOrganDamage: false,
          dmRiskFactorsCount: 0,
          ckd: "none",
          hasFh: false,
          fhHasMajorRiskFactor: false,
          hasSubclinicalPlaque: true,
          hasPrematureFamilyHistory: false,
          hasLpaElevated: true,
          hasHiv: false,
          hasCancerToxicityRisk: false,
          useDietarySupplements: false
        }
      },
      {
        id: "p2-v6",
        visitDate: "Tuần 20 (Tái khám)",
        clinicalNotes: "Tái khám tuần 20. Bệnh nhân tích cực duy trì lối sống lành mạnh, ăn kiêng và tập đi bộ nhẹ. Tiếp tục duy trì điều trị thuốc Bempedoic + Ezetimibe + PCSK9i.",
        patientData: {
          name: "Trần Thị B",
          age: 62,
          sex: "female",
          riskRegion: "very_high",
          smokingStatus: true,
          sbp: 124,
          dbp: 78,
          totalChol: 3.9,
          hdlChol: 1.0,
          ldlChol: 1.3,
          triglycerides: 1.7,
          unit: "mmol",
          hasAscvd: true,
          ascvdType: "secondary",
          diabetes: "none",
          dmDuration: 0,
          dmTargetOrganDamage: false,
          dmRiskFactorsCount: 0,
          ckd: "none",
          hasFh: false,
          fhHasMajorRiskFactor: false,
          hasSubclinicalPlaque: true,
          hasPrematureFamilyHistory: false,
          hasLpaElevated: true,
          hasHiv: false,
          hasCancerToxicityRisk: false,
          useDietarySupplements: false
        }
      },
      {
        id: "p2-v7",
        visitDate: "Tuần 24 (Tái khám)",
        clinicalNotes: "Tái khám định kỳ 6 tháng. Kiểm tra chức năng gan thận thấy eGFR bình thường, men gan bình thường. Mỡ máu đạt mục tiêu xuất sắc.",
        patientData: {
          name: "Trần Thị B",
          age: 62,
          sex: "female",
          riskRegion: "very_high",
          smokingStatus: true,
          sbp: 122,
          dbp: 75,
          totalChol: 3.8,
          hdlChol: 1.0,
          ldlChol: 1.28,
          triglycerides: 1.65,
          unit: "mmol",
          hasAscvd: true,
          ascvdType: "secondary",
          diabetes: "none",
          dmDuration: 0,
          dmTargetOrganDamage: false,
          dmRiskFactorsCount: 0,
          ckd: "none",
          hasFh: false,
          fhHasMajorRiskFactor: false,
          hasSubclinicalPlaque: true,
          hasPrematureFamilyHistory: false,
          hasLpaElevated: true,
          hasHiv: false,
          hasCancerToxicityRisk: false,
          useDietarySupplements: false
        }
      },
      {
        id: "p2-v8",
        visitDate: "Tuần 28 (Tái khám)",
        clinicalNotes: "Kiểm tra định kỳ tuần 28. Bệnh nhân khỏe mạnh, vết mổ mạch vành và các vị trí đặt stent hoạt động tốt. Tiếp tục duy trì phác đồ.",
        patientData: {
          name: "Trần Thị B",
          age: 62,
          sex: "female",
          riskRegion: "very_high",
          smokingStatus: true,
          sbp: 122,
          dbp: 75,
          totalChol: 3.8,
          hdlChol: 1.0,
          ldlChol: 1.3,
          triglycerides: 1.6,
          unit: "mmol",
          hasAscvd: true,
          ascvdType: "secondary",
          diabetes: "none",
          dmDuration: 0,
          dmTargetOrganDamage: false,
          dmRiskFactorsCount: 0,
          ckd: "none",
          hasFh: false,
          fhHasMajorRiskFactor: false,
          hasSubclinicalPlaque: true,
          hasPrematureFamilyHistory: false,
          hasLpaElevated: true,
          hasHiv: false,
          hasCancerToxicityRisk: false,
          useDietarySupplements: false
        }
      },
      {
        id: "p2-v9",
        visitDate: "Tuần 36 (Tái khám)",
        clinicalNotes: "Tái khám tuần 36. Các xét nghiệm tim mạch chuyên sâu (siêu âm tim, điện tâm đồ) cho kết quả rất khả quan. Tiếp tục duy trì phác đồ mỡ máu ổn định.",
        patientData: {
          name: "Trần Thị B",
          age: 62,
          sex: "female",
          riskRegion: "very_high",
          smokingStatus: true,
          sbp: 120,
          dbp: 75,
          totalChol: 3.8,
          hdlChol: 1.0,
          ldlChol: 1.25,
          triglycerides: 1.6,
          unit: "mmol",
          hasAscvd: true,
          ascvdType: "secondary",
          diabetes: "none",
          dmDuration: 0,
          dmTargetOrganDamage: false,
          dmRiskFactorsCount: 0,
          ckd: "none",
          hasFh: false,
          fhHasMajorRiskFactor: false,
          hasSubclinicalPlaque: true,
          hasPrematureFamilyHistory: false,
          hasLpaElevated: true,
          hasHiv: false,
          hasCancerToxicityRisk: false,
          useDietarySupplements: false
        }
      },
      {
        id: "p2-v10",
        visitDate: "Tuần 52 (Tròn 1 năm)",
        clinicalNotes: "Tái khám tròn 1 năm sau biến cố ACS mạch vành nguy kịch. Sức khỏe tim mạch của bệnh nhân được bảo vệ tối ưu. LDL-C duy trì cực tốt ở mức 1.1 mmol/L nhờ liệu pháp phối hợp Bempedoic + Ezetimibe + PCSK9i. Một thành công lâm sàng rực rỡ theo đúng ESC 2025.",
        patientData: {
          name: "Trần Thị B",
          age: 62,
          sex: "female",
          riskRegion: "very_high",
          smokingStatus: true,
          sbp: 120,
          dbp: 75,
          totalChol: 3.6,
          hdlChol: 1.0,
          ldlChol: 1.1,
          triglycerides: 1.5,
          unit: "mmol",
          hasAscvd: true,
          ascvdType: "secondary",
          diabetes: "none",
          dmDuration: 0,
          dmTargetOrganDamage: false,
          dmRiskFactorsCount: 0,
          ckd: "none",
          hasFh: false,
          fhHasMajorRiskFactor: false,
          hasSubclinicalPlaque: true,
          hasPrematureFamilyHistory: false,
          hasLpaElevated: true,
          hasHiv: false,
          hasCancerToxicityRisk: false,
          useDietarySupplements: false
        }
      }
    ]
  },
  {
    id: "patient3",
    patientName: "Phạm Văn C (Suy thận & Đái tháo đường - 7 Visits - Tử vong)",
    status: "deceased",
    visits: [
      {
        id: "p3-v1",
        visitDate: "Tuần 0 (Sau mổ CABG)",
        clinicalNotes: "Bệnh nhân nam 68 tuổi, vừa phẫu thuật bắc cầu chủ-vành (CABG). Bệnh nền phức tạp: Đái tháo đường biến chứng thận mạn (CKD độ 3, eGFR = 35). LDL-C nền 3.8 mmol/L, Lp(a) cực cao 120 mg/dL (nguy cơ tồn dư xơ vữa cực lớn). Khởi trị đề xuất: Rosuvastatin 40mg + Ezetimibe 10mg.",
        patientData: {
          name: "Phạm Văn C",
          age: 68,
          sex: "male",
          riskRegion: "high",
          smokingStatus: false,
          sbp: 165,
          dbp: 95,
          totalChol: 6.8,
          hdlChol: 0.9,
          ldlChol: 3.8,
          triglycerides: 3.2,
          unit: "mmol",
          hasAscvd: true,
          ascvdType: "secondary",
          diabetes: "t2dm",
          dmDuration: 15,
          dmTargetOrganDamage: true,
          dmRiskFactorsCount: 2,
          ckd: "moderate",
          hasFh: false,
          fhHasMajorRiskFactor: false,
          hasSubclinicalPlaque: true,
          hasPrematureFamilyHistory: false,
          hasLpaElevated: true,
          hasHiv: false,
          hasCancerToxicityRisk: false,
          useDietarySupplements: false
        }
      },
      {
        id: "p3-v2",
        visitDate: "Tuần 6 (Tái khám)",
        clinicalNotes: "Tái khám tuần 6. LDL-C giảm xuống 1.9 mmol/L (~50% giảm). Vẫn chưa đạt đích rất cao (< 1.4 mmol/L). Huyết áp còn cao. Quyết định thêm Bempedoic Acid 180mg để hạ sâu thêm mỡ máu cho nhóm nguy cơ rất cao này.",
        patientData: {
          name: "Phạm Văn C",
          age: 68,
          sex: "male",
          riskRegion: "high",
          smokingStatus: false,
          sbp: 150,
          dbp: 90,
          totalChol: 4.9,
          hdlChol: 0.9,
          ldlChol: 1.9,
          triglycerides: 2.8,
          unit: "mmol",
          hasAscvd: true,
          ascvdType: "secondary",
          diabetes: "t2dm",
          dmDuration: 15,
          dmTargetOrganDamage: true,
          dmRiskFactorsCount: 2,
          ckd: "moderate",
          hasFh: false,
          fhHasMajorRiskFactor: false,
          hasSubclinicalPlaque: true,
          hasPrematureFamilyHistory: false,
          hasLpaElevated: true,
          hasHiv: false,
          hasCancerToxicityRisk: false,
          useDietarySupplements: false
        }
      },
      {
        id: "p3-v3",
        visitDate: "Tuần 12 (Đau khớp)",
        clinicalNotes: "Tái khám tuần 12. LDL-C giảm nhẹ còn 1.6 mmol/L. Huyết áp cải thiện. Bệnh nhân tuân thủ thuốc rất tốt nhưng bắt đầu xuất hiện những cơn đau nhức dữ dội sưng tấy đỏ ở khớp ngón chân cái bên phải.",
        patientData: {
          name: "Phạm Văn C",
          age: 68,
          sex: "male",
          riskRegion: "high",
          smokingStatus: false,
          sbp: 145,
          dbp: 88,
          totalChol: 4.6,
          hdlChol: 0.9,
          ldlChol: 1.6,
          triglycerides: 2.5,
          unit: "mmol",
          hasAscvd: true,
          ascvdType: "secondary",
          diabetes: "t2dm",
          dmDuration: 15,
          dmTargetOrganDamage: true,
          dmRiskFactorsCount: 2,
          ckd: "moderate",
          hasFh: false,
          fhHasMajorRiskFactor: false,
          hasSubclinicalPlaque: true,
          hasPrematureFamilyHistory: false,
          hasLpaElevated: true,
          hasHiv: false,
          hasCancerToxicityRisk: false,
          useDietarySupplements: false
        }
      },
      {
        id: "p3-v4",
        visitDate: "Tuần 18 (Gút cấp)",
        clinicalNotes: "Cơn gút cấp bùng phát dữ dội do tác dụng phụ làm tăng acid uric máu của Bempedoic Acid trên nền suy thận sẵn eGFR = 35. Buộc lòng phải dừng hẳn Bempedoic Acid. LDL-C lập tức tăng vọt trở lại lên 2.1 mmol/L. Bệnh nhân lo lắng, tim mạch bất ổn.",
        patientData: {
          name: "Phạm Văn C",
          age: 68,
          sex: "male",
          riskRegion: "high",
          smokingStatus: false,
          sbp: 142,
          dbp: 88,
          totalChol: 5.1,
          hdlChol: 0.9,
          ldlChol: 2.1,
          triglycerides: 2.6,
          unit: "mmol",
          hasAscvd: true,
          ascvdType: "secondary",
          diabetes: "t2dm",
          dmDuration: 15,
          dmTargetOrganDamage: true,
          dmRiskFactorsCount: 2,
          ckd: "moderate",
          hasFh: false,
          fhHasMajorRiskFactor: false,
          hasSubclinicalPlaque: true,
          hasPrematureFamilyHistory: false,
          hasLpaElevated: true,
          hasHiv: false,
          hasCancerToxicityRisk: false,
          useDietarySupplements: false
        }
      },
      {
        id: "p3-v5",
        visitDate: "Tuần 24 (Tái khám)",
        clinicalNotes: "Đã khống chế hoàn toàn cơn gút cấp. Bác sĩ quyết định bổ sung kháng thể đơn dòng PCSK9 inhibitor (Evolocumab 140mg tiêm dưới da mỗi 2 tuần) thay thế cho bempedoic acid. LDL-C giảm sâu xuống 1.3 mmol/L, thành công đạt đích huyết áp 135 mmHg.",
        patientData: {
          name: "Phạm Văn C",
          age: 68,
          sex: "male",
          riskRegion: "high",
          smokingStatus: false,
          sbp: 135,
          dbp: 85,
          totalChol: 4.3,
          hdlChol: 0.9,
          ldlChol: 1.3,
          triglycerides: 2.3,
          unit: "mmol",
          hasAscvd: true,
          ascvdType: "secondary",
          diabetes: "t2dm",
          dmDuration: 15,
          dmTargetOrganDamage: true,
          dmRiskFactorsCount: 2,
          ckd: "moderate",
          hasFh: false,
          fhHasMajorRiskFactor: false,
          hasSubclinicalPlaque: true,
          hasPrematureFamilyHistory: false,
          hasLpaElevated: true,
          hasHiv: false,
          hasCancerToxicityRisk: false,
          useDietarySupplements: false
        }
      },
      {
        id: "p3-v6",
        visitDate: "Tuần 30 (Bỏ thuốc)",
        clinicalNotes: "Bệnh nhân tự ý bỏ tiêm PCSK9 inhibitor vì chi phí thuốc quá cao nằm ngoài khả năng chi trả. Nguy hại hơn, bệnh nhân tự ý mua thực phẩm chức năng tự phát trên mạng để tự điều trị mỡ máu (Chống chỉ định Class III - ESC 2025). LDL-C lập tức tăng vọt lên 1.9 mmol/L, huyết áp bất ổn.",
        patientData: {
          name: "Phạm Văn C",
          age: 68,
          sex: "male",
          riskRegion: "high",
          smokingStatus: false,
          sbp: 140,
          dbp: 88,
          totalChol: 4.9,
          hdlChol: 0.9,
          ldlChol: 1.9,
          triglycerides: 2.5,
          unit: "mmol",
          hasAscvd: true,
          ascvdType: "secondary",
          diabetes: "t2dm",
          dmDuration: 15,
          dmTargetOrganDamage: true,
          dmRiskFactorsCount: 2,
          ckd: "moderate",
          hasFh: false,
          fhHasMajorRiskFactor: false,
          hasSubclinicalPlaque: true,
          hasPrematureFamilyHistory: false,
          hasLpaElevated: true,
          hasHiv: false,
          hasCancerToxicityRisk: false,
          useDietarySupplements: true
        }
      },
      {
        id: "p3-v7",
        visitDate: "Tuần 36 (KHÔNG QUA KHỎI)",
        isFatalOutcome: true,
        clinicalNotes: "BỆNH NHÂN ĐÃ TỬ VONG DỘT NGỘT DO BIẾN CỐ TIM MẠCH CẤP (NHỒI MÁU CƠ TIM CẤP DIỆN RỘNG TÁI PHÁT). Sự phối hợp của nhiều yếu tố nguy cơ cực lớn (ĐTĐ biến chứng thận nặng CKD, Lp(a) rất cao làm mảng xơ vữa bất ổn phát triển cực nhanh, kết hợp với việc ngưng tuân thủ điều trị PCSK9i vì rào cản chi phí và tự ý dùng TPCN tự phát) đã dẫn đến kết cục lâm sàng thương tâm này. Đây là bài học sâu sắc về quản lý tuân thủ điều trị và nguy cơ tồn dư (residual risk) rất lớn trong tim mạch.",
        patientData: {
          name: "Phạm Văn C",
          age: 68,
          sex: "male",
          riskRegion: "high",
          smokingStatus: false,
          sbp: 145,
          dbp: 90,
          totalChol: 5.2,
          hdlChol: 0.9,
          ldlChol: 2.2,
          triglycerides: 2.6,
          unit: "mmol",
          hasAscvd: true,
          ascvdType: "secondary",
          diabetes: "t2dm",
          dmDuration: 15,
          dmTargetOrganDamage: true,
          dmRiskFactorsCount: 2,
          ckd: "moderate",
          hasFh: false,
          fhHasMajorRiskFactor: false,
          hasSubclinicalPlaque: true,
          hasPrematureFamilyHistory: false,
          hasLpaElevated: true,
          hasHiv: false,
          hasCancerToxicityRisk: false,
          useDietarySupplements: true
        }
      }
    ]
  }
];
